apiVersion: v1
kind: ServiceAccount
metadata:
  name: pizza-controller
  namespace: opstips-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pizza-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pizza-controller
subjects:
  - kind: ServiceAccount
    name: pizza-controller
    namespace: opstips-system
